project_id = "htppstmurohrfvoyviat"

[functions.send-delivery-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-refund-status-email]
verify_jwt = false

[functions.initialize-paystack]
verify_jwt = false

[functions.verify-paystack]
verify_jwt = false
