// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjgnmkjjnruwctpupvxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqZ25ta2pqbnJ1d2N0cHVwdnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTg0NTcsImV4cCI6MjA2NDU5NDQ1N30.lkCVBA6B6xRrFF8bKgZFDIzcORQy6vx1UxNU2SvDM2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);